# Generated by Django 3.2.12 on 2023-02-28 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0002_auto_20230228_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='sousmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pcs', to='pcs.sousmodel'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='stockage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pcs', to='pcs.stokage'),
        ),
    ]
