# Generated by Django 3.2.12 on 2023-02-13 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=20)),
                ('magasin_photo', models.ImageField(default='magasin_photo/default-mag.png', upload_to='magasin_photo')),
                ('description', models.TextField()),
                ('lien_facebook', models.CharField(max_length=50)),
                ('lien_instagram', models.CharField(max_length=50)),
                ('lien_snapshat', models.CharField(max_length=50)),
                ('rank', models.FloatField()),
                ('adress', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Horeureur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heur_debut', models.TimeField()),
                ('heur_fin', models.TimeField()),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbdd.jour')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbdd.magasin')),
            ],
        ),
    ]
