# Generated by Django 3.2.12 on 2023-02-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0002_horeureur_jour_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='magasins',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainbdd.magasin'),
        ),
    ]
