# Generated by Django 3.2.12 on 2023-02-13 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0003_utilisateur_magasins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='magasins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbdd.magasin'),
        ),
    ]
