# Generated by Django 3.2.12 on 2023-02-13 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0005_alter_utilisateur_magasins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='magasins',
        ),
        migrations.AddField(
            model_name='magasin',
            name='parton',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainbdd.utilisateur'),
        ),
    ]
