# Generated by Django 3.2.12 on 2023-02-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0007_utilisateur_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_photo', models.ImageField(upload_to='categorie_photo')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='fav',
            field=models.ManyToManyField(blank=True, to='mainbdd.Magasin'),
        ),
    ]
