# Generated by Django 3.2.12 on 2023-02-13 22:41

from django.db import migrations, models
import django.db.models.deletion
import mainbdd.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0009_magasin_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prix', models.FloatField()),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbdd.magasin')),
            ],
        ),
        migrations.CreateModel(
            name='ServiseNonDispo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heur_debut', models.DateTimeField()),
                ('heur_fin', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbdd.service')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbdd.magasin')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='posts/default.jpg', upload_to=mainbdd.models.upload_to)),
                ('pub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mainbdd.publication')),
            ],
        ),
    ]
