# Generated by Django 3.2.12 on 2023-02-14 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0011_auto_20230214_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mainbdd.publication'),
        ),
    ]
