# Generated by Django 3.2.12 on 2023-02-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0012_alter_photos_pub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heur_debut', models.TimeField()),
                ('heur_fin', models.TimeField()),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horeur', to='mainbdd.jour')),
            ],
        ),
        migrations.AlterField(
            model_name='magasin',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magasins', to='mainbdd.categorie'),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='parton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedMagasins', to='mainbdd.utilisateur'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='mainbdd.magasin'),
        ),
        migrations.AlterField(
            model_name='servisenondispo',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponible', to='mainbdd.service'),
        ),
        migrations.DeleteModel(
            name='Horeureur',
        ),
        migrations.AddField(
            model_name='horeur',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horeur', to='mainbdd.magasin'),
        ),
    ]
