# Generated by Django 3.2.12 on 2023-02-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0013_auto_20230214_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magasin',
            name='photo',
        ),
    ]
