# Generated by Django 3.2.12 on 2023-02-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0015_auto_20230215_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin',
            name='nom',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
