# Generated by Django 3.2.12 on 2023-02-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0017_magasin_lien_de_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasin',
            name='lien_de_verification',
            field=models.CharField(max_length=200),
        ),
    ]
