# Generated by Django 3.2.12 on 2023-02-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0019_magasin_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horeur',
            name='jour',
        ),
    ]
