# Generated by Django 3.2.12 on 2023-02-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0020_remove_horeur_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horeur',
            name='heur_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='horeur',
            name='heur_fin',
            field=models.DateTimeField(),
        ),
    ]
