# Generated by Django 3.2.12 on 2023-02-16 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0023_alter_horeur_jour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heur_debut', models.TimeField()),
                ('heur_fin', models.TimeField()),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Horaires', to='mainbdd.jour')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horeurs', to='mainbdd.magasin')),
            ],
        ),
        migrations.DeleteModel(
            name='Horeur',
        ),
    ]
