# Generated by Django 3.2.12 on 2023-02-16 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0024_auto_20230216_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='jour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbdd.jour'),
        ),
    ]
