# Generated by Django 3.2.12 on 2023-02-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0025_alter_horaire_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rank',
            field=models.FloatField(default=0),
        ),
    ]
