# Generated by Django 3.2.12 on 2023-02-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0028_alter_service_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='servisenondispo',
            name='jour',
            field=models.CharField(default='', max_length=50),
        ),
    ]
