# Generated by Django 3.2.12 on 2023-02-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0030_alter_servisenondispo_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servisenondispo',
            name='heur_debut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='servisenondispo',
            name='heur_fin',
            field=models.TimeField(),
        ),
    ]
