# Generated by Django 3.2.12 on 2023-02-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0031_auto_20230220_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiseNonDispo',
            new_name='ServiceDispo',
        ),
    ]
